/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendacurso.TelasFuncionario;

/**
 *
 * @author renan_8tvcd4n
 */
public class Tela_Cadastro_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastro
     */
    public Tela_Cadastro_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JPanel_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_Logo_BarraLateral_Tale_Cadastro_Funcionario = new javax.swing.JLabel();
        JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_iconeTreinamento_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        JPanel_Fundo_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_Title_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jst_Separator = new javax.swing.JSeparator();
        JPanel_imgFuncionario_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_imgFuncionario_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jlbl_conteinerDeCampos_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        JPanel_identificaocontainer_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        JPanel_identiConteinar_Tela_cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_Matricula_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Matricula_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_CPF_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_cpf_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Sobrenome_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Sobrenome_Tela_cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Nome_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Nome_Tela_cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_h2_Identificacao_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        JPanel_ContatoConteiner_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        JPanel_contatConteiner_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlabl_Email_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Email__Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Celular_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Celular_Tela_Cadatro_Funcionario = new javax.swing.JTextField();
        JPanel_DescConteiner_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_Equipe_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Equipe_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Turno_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jlbl_Admissao_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Admissao_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Setor_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Setor_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jcbx_Turno_Tela_Cadastro_Funcionario = new javax.swing.JComboBox<>();
        Jbtn_Cancelar_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_Salvar_Tela_Cadastro_Funcionario = new javax.swing.JButton();

        Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(193, 200, 4));
        Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconeCadastrarFuncionario.png"))); // NOI18N
        Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(100, 70));
        Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioVetoableChange(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(47, 63, 115));
        JPanel_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(232, 832));

        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout.png"))); // NOI18N
        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario.setMaximumSize(new java.awt.Dimension(40, 40));
        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario.setMinimumSize(new java.awt.Dimension(40, 40));
        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(40, 40));
        Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(47, 63, 115));
        JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(133, 143));

        Jlbl_Logo_BarraLateral_Tale_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoBarraLateral.png"))); // NOI18N

        javax.swing.GroupLayout JPanel_logo_Barra_Lateral_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario);
        JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario.setLayout(JPanel_logo_Barra_Lateral_Tela_Cadastro_FuncionarioLayout);
        JPanel_logo_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_logo_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlbl_Logo_BarraLateral_Tale_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanel_logo_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_logo_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlbl_Logo_BarraLateral_Tale_Cadastro_Funcionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(40, 54, 98));
        JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(232, 40));

        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(40, 54, 98));
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setText("Funcionário");
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setAlignmentX(0.5F);
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setBorder(null);
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setIconTextGap(30);
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setMargin(new java.awt.Insets(0, 0, 0, 10));
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setMaximumSize(new java.awt.Dimension(170, 30));
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setMinimumSize(new java.awt.Dimension(170, 30));
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(232, 45));
        Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Funcionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeFuncionarioComFundo.png"))); // NOI18N
        Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario);
        JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario.setLayout(JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout);
        JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addComponent(Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_contentFuncionarioButton_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addComponent(Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(40, 54, 98));
        JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario.setMaximumSize(new java.awt.Dimension(232, 46));
        JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario.setMinimumSize(new java.awt.Dimension(232, 46));

        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(40, 54, 98));
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setText("Equipe");
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setAlignmentX(0.5F);
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setBorder(null);
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setIconTextGap(30);
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setMargin(new java.awt.Insets(0, 0, 0, 10));
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setMaximumSize(new java.awt.Dimension(170, 30));
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setMinimumSize(new java.awt.Dimension(170, 30));
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(232, 45));
        Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Equipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeEquipeComFundo.png"))); // NOI18N
        Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_contentEquipe_BarraLateral_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario);
        JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario.setLayout(JPanel_contentEquipe_BarraLateral_Tela_Cadastro_FuncionarioLayout);
        JPanel_contentEquipe_BarraLateral_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_contentEquipe_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_contentEquipe_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanel_contentEquipe_BarraLateral_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_contentEquipe_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(40, 54, 98));
        Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(232, 45));

        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(40, 54, 98));
        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario.setText("Treinamento");
        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario.setBorder(null);
        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(160, 45));
        Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Treinamento_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jbtn_iconeTreinamento_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_iconeTreinamento_BarraLateral_Tela_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeTreinamento.png"))); // NOI18N
        Jbtn_iconeTreinamento_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(65, 32));

        javax.swing.GroupLayout Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario);
        Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario.setLayout(Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout);
        Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Jbtn_iconeTreinamento_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jbtn_iconeTreinamento_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeTrocaUsario.png"))); // NOI18N
        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario.setMaximumSize(new java.awt.Dimension(80, 40));
        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario.setMinimumSize(new java.awt.Dimension(80, 40));
        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(80, 40));
        Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeConfiguracao.png"))); // NOI18N
        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario.setMaximumSize(new java.awt.Dimension(90, 40));
        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario.setMinimumSize(new java.awt.Dimension(90, 40));
        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(90, 40));
        Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Configuração_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_BarraLateral_Tela_Cadastro_Funcionario);
        JPanel_BarraLateral_Tela_Cadastro_Funcionario.setLayout(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout);
        JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addComponent(Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanel_BarraLateral_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JPanel_Fundo_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        JPanel_Fundo_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(1048, 832));

        JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(135, 105));

        Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(242, 237, 228));
        Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario.setText("Adicionar");
        Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(135, 45));

        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(242, 237, 228));
        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario.setText("Pesquisar");
        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(135, 45));
        Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_conteinerBotoes_Fundo_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario);
        JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario.setLayout(JPanel_conteinerBotoes_Fundo_Tela_Cadastro_FuncionarioLayout);
        JPanel_conteinerBotoes_Fundo_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_conteinerBotoes_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanel_conteinerBotoes_Fundo_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_conteinerBotoes_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_conteinerBotoes_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addComponent(Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(800, 730));

        Jlbl_Title_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Jlbl_Title_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Title_Tela_Cadastro_Funcionario.setText("Cadastro de Funcionário");
        Jlbl_Title_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(160, 55));

        Jst_Separator.setPreferredSize(new java.awt.Dimension(885, 10));

        Jlbl_imgFuncionario_Tela_Cadastro_Funcionario.setText("img");
        Jlbl_imgFuncionario_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_imgFuncionario_Tela_Cadastro_Funcionario);
        JPanel_imgFuncionario_Tela_Cadastro_Funcionario.setLayout(JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout);
        JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Jlbl_imgFuncionario_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_imgFuncionario_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jlbl_imgFuncionario_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Jlbl_conteinerDeCampos_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));

        JPanel_identificaocontainer_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));

        JPanel_identiConteinar_Tela_cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        JPanel_identiConteinar_Tela_cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanel_identiConteinar_Tela_cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(470, 100));

        Jlbl_Matricula_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Matricula_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Matricula_Tela_Cadastro_Funcionario.setText("Matricula:");

        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setText("00000000000");
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(103, 25));
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Matricula_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jlbl_CPF_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_CPF_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_CPF_Tela_Cadastro_Funcionario.setText("CPF:");

        Jtxtf_cpf_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_cpf_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_cpf_Tela_Cadastro_Funcionario.setText("000.000.000-00");
        Jtxtf_cpf_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(103, 25));
        Jtxtf_cpf_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_cpf_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jlbl_Sobrenome_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Sobrenome_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Sobrenome_Tela_Cadastro_Funcionario.setText("Sobrenome:");

        Jtxtf_Sobrenome_Tela_cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Sobrenome_Tela_cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Sobrenome_Tela_cadastro_Funcionario.setMinimumSize(new java.awt.Dimension(64, 25));
        Jtxtf_Sobrenome_Tela_cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(104, 25));
        Jtxtf_Sobrenome_Tela_cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Sobrenome_Tela_cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jlbl_Nome_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Nome_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Nome_Tela_Cadastro_Funcionario.setText("Nome:");

        Jtxtf_Nome_Tela_cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Nome_Tela_cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Nome_Tela_cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(70, 25));
        Jtxtf_Nome_Tela_cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Nome_Tela_cadastro_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_identiConteinar_Tela_cadastro_Funcionario);
        JPanel_identiConteinar_Tela_cadastro_Funcionario.setLayout(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout);
        JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Nome_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxtf_Nome_Tela_cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Matricula_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxtf_Matricula_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_CPF_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxtf_cpf_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Sobrenome_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxtf_Sobrenome_Tela_cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_Matricula_Tela_Cadastro_Funcionario)
                    .addComponent(Jtxtf_Matricula_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlbl_CPF_Tela_Cadastro_Funcionario)
                    .addComponent(Jtxtf_cpf_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jlbl_Sobrenome_Tela_Cadastro_Funcionario)
                        .addComponent(Jtxtf_Sobrenome_Tela_cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanel_identiConteinar_Tela_cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jlbl_Nome_Tela_Cadastro_Funcionario)
                        .addComponent(Jtxtf_Nome_Tela_cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        Jlbl_h2_Identificacao_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Jlbl_h2_Identificacao_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_h2_Identificacao_Tela_Cadastro_Funcionario.setText("Identificação");

        javax.swing.GroupLayout JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_identificaocontainer_Tela_Cadastro_Funcionario);
        JPanel_identificaocontainer_Tela_Cadastro_Funcionario.setLayout(JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout);
        JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_identiConteinar_Tela_cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jlbl_h2_Identificacao_Tela_Cadastro_Funcionario)
                .addGap(216, 216, 216))
        );
        JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_identificaocontainer_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Jlbl_h2_Identificacao_Tela_Cadastro_Funcionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanel_identiConteinar_Tela_cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPanel_ContatoConteiner_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));

        JPanel_contatConteiner_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        JPanel_contatConteiner_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanel_contatConteiner_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(470, 100));

        Jlabl_Email_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlabl_Email_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlabl_Email_Tela_Cadastro_Funcionario.setText("Email:");

        Jtxtf_Email__Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Email__Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Email__Tela_Cadastro_Funcionario.setText("usermail@gmail.com");
        Jtxtf_Email__Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Email__Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jlbl_Celular_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Celular_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Celular_Tela_Cadastro_Funcionario.setText("Celular:");

        Jtxtf_Celular_Tela_Cadatro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Celular_Tela_Cadatro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Celular_Tela_Cadatro_Funcionario.setText("(DDD) X XXXX-XXXX");

        javax.swing.GroupLayout JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_contatConteiner_Tela_Cadastro_Funcionario);
        JPanel_contatConteiner_Tela_Cadastro_Funcionario.setLayout(JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout);
        JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Jlabl_Email_Tela_Cadastro_Funcionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jtxtf_Email__Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jlbl_Celular_Tela_Cadastro_Funcionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jtxtf_Celular_Tela_Cadatro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(JPanel_contatConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabl_Email_Tela_Cadastro_Funcionario)
                    .addComponent(Jtxtf_Email__Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlbl_Celular_Tela_Cadastro_Funcionario)
                    .addComponent(Jtxtf_Celular_Tela_Cadatro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JPanel_DescConteiner_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        JPanel_DescConteiner_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Jlbl_Equipe_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Equipe_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Equipe_Tela_Cadastro_Funcionario.setText("Equipe:");

        Jtxtf_Equipe_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Equipe_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Equipe_Tela_Cadastro_Funcionario.setText("X00000000000");
        Jtxtf_Equipe_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(71, 25));
        Jtxtf_Equipe_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Equipe_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jlbl_Turno_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Turno_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Turno_Tela_Cadastro_Funcionario.setText("Turno:");

        Jlbl_Admissao_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Admissao_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Admissao_Tela_Cadastro_Funcionario.setText("Admissão:");

        Jtxtf_Admissao_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Admissao_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Admissao_Tela_Cadastro_Funcionario.setText("DD/MM/AAAA");
        Jtxtf_Admissao_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(87, 25));

        Jlbl_Setor_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Jlbl_Setor_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Setor_Tela_Cadastro_Funcionario.setText("Setor:");

        Jtxtf_Setor_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Setor_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Setor_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(77, 25));

        Jcbx_Turno_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jcbx_Turno_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jcbx_Turno_Tela_Cadastro_Funcionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecionar --", "Matutino", "Vespertino", "Noturno" }));
        Jcbx_Turno_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcbx_Turno_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_DescConteiner_Tela_Cadastro_Funcionario);
        JPanel_DescConteiner_Tela_Cadastro_Funcionario.setLayout(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout);
        JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Setor_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxtf_Setor_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Equipe_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxtf_Equipe_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Turno_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jcbx_Turno_Tela_Cadastro_Funcionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Admissao_Tela_Cadastro_Funcionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxtf_Admissao_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_Equipe_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtxtf_Equipe_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlbl_Admissao_Tela_Cadastro_Funcionario)
                    .addComponent(Jtxtf_Admissao_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel_DescConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_Setor_Tela_Cadastro_Funcionario)
                    .addComponent(Jtxtf_Setor_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlbl_Turno_Tela_Cadastro_Funcionario)
                    .addComponent(Jcbx_Turno_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanel_ContatoConteiner_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_ContatoConteiner_Tela_Cadastro_Funcionario);
        JPanel_ContatoConteiner_Tela_Cadastro_Funcionario.setLayout(JPanel_ContatoConteiner_Tela_Cadastro_FuncionarioLayout);
        JPanel_ContatoConteiner_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_ContatoConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_DescConteiner_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanel_contatConteiner_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        JPanel_ContatoConteiner_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_ContatoConteiner_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_ContatoConteiner_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addComponent(JPanel_contatConteiner_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanel_DescConteiner_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(153, 0, 0));
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setText("Cancelar");
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(180, 60));
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        Jbtn_Salvar_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setText("Salvar");
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(180, 60));
        Jbtn_Salvar_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Salvar_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(Jlbl_conteinerDeCampos_Tela_Cadastro_Funcionario);
        Jlbl_conteinerDeCampos_Tela_Cadastro_Funcionario.setLayout(Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout);
        Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanel_identificaocontainer_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jbtn_Cancelar_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jbtn_Salvar_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPanel_ContatoConteiner_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JPanel_identificaocontainer_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanel_ContatoConteiner_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jlbl_conteinerDeCampos_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtn_Cancelar_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbtn_Salvar_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario);
        JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario.setLayout(JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout);
        JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Jst_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_conteinerDeCampos_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(JPanel_imgFuncionario_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addComponent(Jlbl_Title_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))))
        );
        JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_abaConteiner_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Jlbl_Title_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jst_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanel_imgFuncionario_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jlbl_conteinerDeCampos_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout JPanel_Fundo_Tela_Cadastro_FuncionarioLayout = new javax.swing.GroupLayout(JPanel_Fundo_Tela_Cadastro_Funcionario);
        JPanel_Fundo_Tela_Cadastro_Funcionario.setLayout(JPanel_Fundo_Tela_Cadastro_FuncionarioLayout);
        JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.setHorizontalGroup(
            JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.setVerticalGroup(
            JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                .addGroup(JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel_Fundo_Tela_Cadastro_FuncionarioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JPanel_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_BarraLateral_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanel_Fundo_Tela_Cadastro_Funcionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Funcionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Funcionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Funcionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Equipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Equipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Equipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Configuração_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Configuração_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Configuração_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioVetoableChange

    private void Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_CadastrarFuncionario_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Salvar_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Salvar_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Salvar_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed

    private void Jcbx_Turno_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcbx_Turno_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcbx_Turno_Tela_Cadastro_FuncionarioActionPerformed

    private void Jtxtf_Equipe_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Equipe_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Equipe_Tela_Cadastro_FuncionarioActionPerformed

    private void Jtxtf_Email__Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Email__Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Email__Tela_Cadastro_FuncionarioActionPerformed

    private void Jtxtf_Nome_Tela_cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Nome_Tela_cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Nome_Tela_cadastro_FuncionarioActionPerformed

    private void Jtxtf_Sobrenome_Tela_cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Sobrenome_Tela_cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Sobrenome_Tela_cadastro_FuncionarioActionPerformed

    private void Jtxtf_cpf_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_cpf_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_cpf_Tela_Cadastro_FuncionarioActionPerformed

    private void Jtxtf_Matricula_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Matricula_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Matricula_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Treinamento_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Treinamento_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Treinamento_BarraLateral_Tela_Cadastro_FuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_ContatoConteiner_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_DescConteiner_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_Fundo_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_abaConteiner_Fundo_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_contatConteiner_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_conteinerBotoes_Fundo_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_contentEquipe_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_contentFuncionarioButton_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_identiConteinar_Tela_cadastro_Funcionario;
    private javax.swing.JPanel JPanel_identificaocontainer_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_imgFuncionario_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel JPanel_logo_Barra_Lateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_AdicionarFuncionario_Fundo_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_CadastrarFuncionario_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Cancelar_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Configuração_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Equipe_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Funcionario_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_IconeFuncionario_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_LogoutButton_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_PesquisarFuncionario_Fundo_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Salvar_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Treinamento_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_iconeEquipe_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_iconeTreinamento_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_trocarUsuario_BarraLateral_Tela_Cadastro_Funcionario;
    private javax.swing.JComboBox<String> Jcbx_Turno_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlabl_Email_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Admissao_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_CPF_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Celular_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Equipe_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Logo_BarraLateral_Tale_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Matricula_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Nome_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Setor_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Sobrenome_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Title_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Turno_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel Jlbl_conteinerDeCampos_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_h2_Identificacao_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_imgFuncionario_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel Jpanel_contentTreinamento_Barra_Lateral_Tela_Cadastro_Funcionario;
    private javax.swing.JSeparator Jst_Separator;
    private javax.swing.JTextField Jtxtf_Admissao_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Celular_Tela_Cadatro_Funcionario;
    private javax.swing.JTextField Jtxtf_Email__Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Equipe_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Matricula_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Nome_Tela_cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Setor_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Sobrenome_Tela_cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_cpf_Tela_Cadastro_Funcionario;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
