/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_configuracao;

import Telas_Iniciais.Tela_Login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author renan_8tvcd4n
 */
public class Credencial extends javax.swing.JFrame {

    /**
     * Creates new form credenciais
     */
    public Credencial() {
        initComponents();
    }
    
    private int userId = Tela_Login.id_usuario;
    
    private boolean validaSenha(String query) throws SQLException{
        String url = "jdbc:mysql://localhost:3306/db_agenda_curso";
        String user = "root";
        String psswrd = "";
        
        boolean isValid = false;
        
        String[] pass = new String[3];
        pass[0] = (String) Jtxtf_newPsswd_CredUser.getText();
        pass[1] = (String) Jtxtf_rNewPsswd_CredUser.getText();
        
        Connection connection = DriverManager.getConnection(url, user, psswrd);
        PreparedStatement statement = connection.prepareStatement(query);
        try{
            ResultSet resultSet = statement.executeQuery();
            
            if(resultSet.next()){
                pass[2] = resultSet.getString("senha");
            }
            
            if (pass[0].length() > 11){
                if(!pass[0].equals(pass[2])){
                    if(pass[0].equals(pass[1])){
                        isValid = true;
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Senhas não compativeis", "ERRO",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Nova senha não pode ser igual a senha anterior", "ERRO",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                 JOptionPane.showMessageDialog(null, "Defina uma senha com no mínimo 12 caracteres", "ERRO",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null , erro.getMessage());
        }
        
        return isValid;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpnl_Conteiner_CredFunc = new javax.swing.JPanel();
        Jlbl_title_credUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Jtxtf_Login_CredUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jtxtf_newPsswd_CredUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Jtxtf_rNewPsswd_CredUser = new javax.swing.JTextField();
        Jbtn_Atualizar_CredUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Jpnl_Conteiner_CredFunc.setBackground(new java.awt.Color(243, 236, 196));
        Jpnl_Conteiner_CredFunc.setMaximumSize(new java.awt.Dimension(400, 300));
        Jpnl_Conteiner_CredFunc.setMinimumSize(new java.awt.Dimension(400, 300));
        Jpnl_Conteiner_CredFunc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_title_credUser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Jlbl_title_credUser.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_title_credUser.setText("Credenciais");
        Jpnl_Conteiner_CredFunc.add(Jlbl_title_credUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login de usuário:");
        Jpnl_Conteiner_CredFunc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 72, -1, 30));

        Jtxtf_Login_CredUser.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Login_CredUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_Login_CredUser.setForeground(new java.awt.Color(0, 0, 0));
        Jtxtf_Login_CredUser.setMaximumSize(new java.awt.Dimension(140, 30));
        Jtxtf_Login_CredUser.setMinimumSize(new java.awt.Dimension(140, 30));
        Jtxtf_Login_CredUser.setPreferredSize(new java.awt.Dimension(140, 30));
        Jpnl_Conteiner_CredFunc.add(Jtxtf_Login_CredUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nova Senha:");
        Jpnl_Conteiner_CredFunc.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        Jtxtf_newPsswd_CredUser.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_newPsswd_CredUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_newPsswd_CredUser.setForeground(new java.awt.Color(0, 0, 0));
        Jtxtf_newPsswd_CredUser.setMaximumSize(new java.awt.Dimension(140, 30));
        Jtxtf_newPsswd_CredUser.setMinimumSize(new java.awt.Dimension(140, 30));
        Jtxtf_newPsswd_CredUser.setPreferredSize(new java.awt.Dimension(140, 30));
        Jpnl_Conteiner_CredFunc.add(Jtxtf_newPsswd_CredUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Repetir Senha:");
        Jpnl_Conteiner_CredFunc.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        Jtxtf_rNewPsswd_CredUser.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_rNewPsswd_CredUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtxtf_rNewPsswd_CredUser.setForeground(new java.awt.Color(0, 0, 0));
        Jtxtf_rNewPsswd_CredUser.setMaximumSize(new java.awt.Dimension(140, 30));
        Jtxtf_rNewPsswd_CredUser.setMinimumSize(new java.awt.Dimension(140, 30));
        Jtxtf_rNewPsswd_CredUser.setPreferredSize(new java.awt.Dimension(140, 30));
        Jpnl_Conteiner_CredFunc.add(Jtxtf_rNewPsswd_CredUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 140, -1));

        Jbtn_Atualizar_CredUser.setBackground(new java.awt.Color(47, 63, 115));
        Jbtn_Atualizar_CredUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Jbtn_Atualizar_CredUser.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_Atualizar_CredUser.setText("Salvar");
        Jbtn_Atualizar_CredUser.setPreferredSize(new java.awt.Dimension(100, 30));
        Jbtn_Atualizar_CredUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Atualizar_CredUserActionPerformed(evt);
            }
        });
        Jpnl_Conteiner_CredFunc.add(Jbtn_Atualizar_CredUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpnl_Conteiner_CredFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpnl_Conteiner_CredFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_Atualizar_CredUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Atualizar_CredUserActionPerformed
        try {
            if(validaSenha("SELECT * FROM usuario WHERE id_usuario = "+this.userId)){
                String url = "jdbc:mysql://localhost:3306/db_agenda_curso";
                String user = "root";
                String psswrd = "";
                
                Connection connection = null;
                PreparedStatement statement = null;
                
                try{
                    connection = DriverManager.getConnection(url, user, psswrd);
                    String query = "UPDATE usuario SET login_usuario = ?, senha = ?, old_psswd = ? WHERE id_usuario ="+this.userId;
                    statement = connection.prepareStatement(query);
                    
                    statement.setString(1, Jtxtf_Login_CredUser.getText());
                    statement.setString(2, Jtxtf_newPsswd_CredUser.getText());
                    statement.setString(3, Jtxtf_rNewPsswd_CredUser.getText());
                    
                    statement.execute();
                    JOptionPane.showMessageDialog(null, "Credencial de usuário atualizada");
                }
                catch (SQLException erro){
                    JOptionPane.showMessageDialog(null, erro.getMessage());
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Credencial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_Jbtn_Atualizar_CredUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String url = "jdbc:mysql://localhost:3306/db_agenda_curso";
        String user = "root";
        String psswrd = "";

        Connection connection = null;
        PreparedStatement statement = null;
        
        try{
            connection = DriverManager.getConnection(url, user, psswrd);
            String query = "SELECT * FROM vw_credfunc WHERE id_usuario ="+this.userId;
            statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();
            
            if(resultSet.next()){
                Jtxtf_Login_CredUser.setText(resultSet.getString("login_usuario"));
            }
        }
        catch (SQLException erro){
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Atualizar_CredUser;
    private javax.swing.JLabel Jlbl_title_credUser;
    private javax.swing.JPanel Jpnl_Conteiner_CredFunc;
    private javax.swing.JTextField Jtxtf_Login_CredUser;
    private javax.swing.JTextField Jtxtf_newPsswd_CredUser;
    private javax.swing.JTextField Jtxtf_rNewPsswd_CredUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
