/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_Funcionario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renan_8tvcd4n
 */
public class PopUp_Treinamentos_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form PopUp_Treinamentos_Funcionario
     */
    public PopUp_Treinamentos_Funcionario() {
        initComponents();
    }

    public void populaTabela(int id_funcionario) throws SQLException{
        String url = "jdbc:mysql://localhost:3306/db_agenda_curso";
        String user = "root";
        String psswrd = "";

        Connection connection = (Connection) DriverManager.getConnection(url, user, psswrd);
        String query = "SELECT * FROM vw_treinofunc WHERE id_funcionario = "+id_funcionario;
        PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);
        
        try{
            statement.execute();
            ResultSet resultSet = statement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) Jtbl_treinamentos.getModel();
            model.setNumRows(0);
            
            while(resultSet.next()){
                model.addRow(new Object[]{
                    resultSet.getString("nome"),
                    resultSet.getString("nome_completo"),
                    resultSet.getString("prev_fim"),
                    resultSet.getString("validade")
                });
            }
            
            connection.close();
            statement.close();
            resultSet.close();
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpnl_fundo_PopTreinos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtbl_treinamentos = new javax.swing.JTable();
        Jlbl_Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Jpnl_fundo_PopTreinos.setBackground(new java.awt.Color(243, 228, 188));

        Jtbl_treinamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jtbl_treinamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "treinamento", "instrutor", "validação", "validade"
            }
        ));
        jScrollPane1.setViewportView(Jtbl_treinamentos);

        Jlbl_Title.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Jlbl_Title.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Title.setText("Treinamentos Realizados");

        javax.swing.GroupLayout Jpnl_fundo_PopTreinosLayout = new javax.swing.GroupLayout(Jpnl_fundo_PopTreinos);
        Jpnl_fundo_PopTreinos.setLayout(Jpnl_fundo_PopTreinosLayout);
        Jpnl_fundo_PopTreinosLayout.setHorizontalGroup(
            Jpnl_fundo_PopTreinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpnl_fundo_PopTreinosLayout.createSequentialGroup()
                .addGroup(Jpnl_fundo_PopTreinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpnl_fundo_PopTreinosLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(Jlbl_Title))
                    .addGroup(Jpnl_fundo_PopTreinosLayout.createSequentialGroup()
                        .addContainerGap(84, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
        Jpnl_fundo_PopTreinosLayout.setVerticalGroup(
            Jpnl_fundo_PopTreinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpnl_fundo_PopTreinosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Jlbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpnl_fundo_PopTreinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpnl_fundo_PopTreinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp_Treinamentos_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp_Treinamentos_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp_Treinamentos_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp_Treinamentos_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp_Treinamentos_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbl_Title;
    private javax.swing.JPanel Jpnl_fundo_PopTreinos;
    private javax.swing.JTable Jtbl_treinamentos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
