/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_Funcionario;

/**
 *
 * @author mathe
 */
public class Tela_Cadastro_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form_Funcionario
     */
    public Tela_Cadastro_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Jlbl_Cadastrar_Tela_Adicionar_Funcionario = new javax.swing.JLabel();
        Jlbl_Foto_Funcionario_Tela_Adicionar_Funcionario = new javax.swing.JLabel();
        Jbtn_Treinamentos_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jpnl_Identificacao_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_Identificacao_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jlbl_Maticula_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Matricula_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Nome_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Nome_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_CPF_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_CPF_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Sobrenome_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Sobrenome_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jpnl_Contato_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_Contato_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jlbl_Numero_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Numero_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jtxtf_Email_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Email_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jpnl_Area_Tela_Cadastro_Funcionario = new javax.swing.JPanel();
        Jlbl_Area_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jlbl_Codigo_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Codigo_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_IdentificacaoEquipe_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Cargo_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jtxtf_Cargo_Tela_Cadastro_Funcionario = new javax.swing.JTextField();
        Jlbl_Turno_Tela_Cadastro_Funcionario = new javax.swing.JLabel();
        Jcbbx_Turno_Tela_Cadastro_Funcionario = new javax.swing.JComboBox<>();
        Jbtn_Salvar_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_Editar_Tela_Cadastro_Funcionario = new javax.swing.JButton();
        Jbtn_Cancelar_Tela_Cadastro_Funcionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(243, 236, 196));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 797));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_Cadastrar_Tela_Adicionar_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Jlbl_Cadastrar_Tela_Adicionar_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Cadastrar_Tela_Adicionar_Funcionario.setText("Cadastro Funcionário");
        Jlbl_Cadastrar_Tela_Adicionar_Funcionario.setPreferredSize(new java.awt.Dimension(351, 49));
        jPanel2.add(Jlbl_Cadastrar_Tela_Adicionar_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        Jlbl_Foto_Funcionario_Tela_Adicionar_Funcionario.setPreferredSize(new java.awt.Dimension(130, 130));
        jPanel2.add(Jlbl_Foto_Funcionario_Tela_Adicionar_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        Jbtn_Treinamentos_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_Treinamentos_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jbtn_Treinamentos_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Treinamentos_Tela_Cadastro_Funcionario.setText("Treinamentos");
        Jbtn_Treinamentos_Tela_Cadastro_Funcionario.setBorder(new javax.swing.border.MatteBorder(null));
        Jbtn_Treinamentos_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel2.add(Jbtn_Treinamentos_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, -1));

        Jpnl_Identificacao_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(780, 171));
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_Identificacao_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Identificacao_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Identificacao_Tela_Cadastro_Funcionario.setText("Identificação");
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jlbl_Identificacao_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Jlbl_Maticula_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Maticula_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Maticula_Tela_Cadastro_Funcionario.setText("Matricula: ");
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jlbl_Maticula_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_Matricula_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jtxtf_Matricula_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        Jlbl_Nome_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Nome_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Nome_Tela_Cadastro_Funcionario.setText("Nome: ");
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jlbl_Nome_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        Jtxtf_Nome_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Nome_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_Nome_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_Nome_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jtxtf_Nome_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        Jlbl_CPF_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_CPF_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_CPF_Tela_Cadastro_Funcionario.setText("CPF:");
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jlbl_CPF_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        Jtxtf_CPF_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_CPF_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_CPF_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_CPF_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jtxtf_CPF_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        Jlbl_Sobrenome_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Sobrenome_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Sobrenome_Tela_Cadastro_Funcionario.setText("Sobrenome: ");
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jlbl_Sobrenome_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        Jtxtf_Sobrenome_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Sobrenome_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_Sobrenome_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_Sobrenome_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jpnl_Identificacao_Tela_Cadastro_Funcionario.add(Jtxtf_Sobrenome_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jPanel2.add(Jpnl_Identificacao_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 223, -1, -1));

        Jpnl_Contato_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jpnl_Contato_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jpnl_Contato_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(780, 114));
        Jpnl_Contato_Tela_Cadastro_Funcionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_Contato_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Contato_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Contato_Tela_Cadastro_Funcionario.setText("Contato");
        Jpnl_Contato_Tela_Cadastro_Funcionario.add(Jlbl_Contato_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Jlbl_Numero_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Numero_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Numero_Tela_Cadastro_Funcionario.setText("Numero:");
        Jpnl_Contato_Tela_Cadastro_Funcionario.add(Jlbl_Numero_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        Jtxtf_Numero_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Numero_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_Numero_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_Numero_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jpnl_Contato_Tela_Cadastro_Funcionario.add(Jtxtf_Numero_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        Jtxtf_Email_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Email_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_Email_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_Email_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jtxtf_Email_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Email_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        Jpnl_Contato_Tela_Cadastro_Funcionario.add(Jtxtf_Email_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        Jlbl_Email_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Email_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Email_Tela_Cadastro_Funcionario.setText("Email:");
        Jpnl_Contato_Tela_Cadastro_Funcionario.add(Jlbl_Email_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel2.add(Jpnl_Contato_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 407, -1, -1));

        Jpnl_Area_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jpnl_Area_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jpnl_Area_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(780, 171));
        Jpnl_Area_Tela_Cadastro_Funcionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_Area_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Area_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Area_Tela_Cadastro_Funcionario.setText("Área/Atuação");
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jlbl_Area_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Jlbl_Codigo_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Codigo_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Codigo_Tela_Cadastro_Funcionario.setText("Código Setor: ");
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jlbl_Codigo_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        Jtxtf_Codigo_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Codigo_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_Codigo_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_Codigo_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jtxtf_Codigo_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Codigo_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jtxtf_Codigo_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        Jlbl_IdentificacaoEquipe_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_IdentificacaoEquipe_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_IdentificacaoEquipe_Tela_Cadastro_Funcionario.setText("Identifição Equipe: ");
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jlbl_IdentificacaoEquipe_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_IdentificacaoEquipe_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        Jlbl_Cargo_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Cargo_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Cargo_Tela_Cadastro_Funcionario.setText("Cargo: ");
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jlbl_Cargo_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        Jtxtf_Cargo_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Cargo_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jtxtf_Cargo_Tela_Cadastro_Funcionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtxtf_Cargo_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jtxtf_Cargo_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        Jlbl_Turno_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Jlbl_Turno_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Turno_Tela_Cadastro_Funcionario.setText("Turno: ");
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jlbl_Turno_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        Jcbbx_Turno_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(255, 255, 255));
        Jcbbx_Turno_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Jcbbx_Turno_Tela_Cadastro_Funcionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Jcbbx_Turno_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(248, 30));
        Jpnl_Area_Tela_Cadastro_Funcionario.add(Jcbbx_Turno_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jPanel2.add(Jpnl_Area_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 534, -1, -1));

        Jbtn_Salvar_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setText("Salvar");
        Jbtn_Salvar_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(151, 35));
        jPanel2.add(Jbtn_Salvar_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 740, -1, -1));

        Jbtn_Editar_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_Editar_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Jbtn_Editar_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Editar_Tela_Cadastro_Funcionario.setText("Editar");
        Jbtn_Editar_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(151, 35));
        Jbtn_Editar_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Editar_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn_Editar_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 740, -1, -1));

        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setText("Cancelar");
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.setPreferredSize(new java.awt.Dimension(151, 35));
        Jbtn_Cancelar_Tela_Cadastro_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn_Cancelar_Tela_Cadastro_Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 740, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 17, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtxtf_Codigo_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Codigo_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Codigo_Tela_Cadastro_FuncionarioActionPerformed

    private void Jtxtf_IdentificacaoEquipe_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_IdentificacaoEquipe_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_IdentificacaoEquipe_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Editar_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Editar_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Editar_Tela_Cadastro_FuncionarioActionPerformed

    private void Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_Cancelar_Tela_Cadastro_FuncionarioActionPerformed

    private void Jtxtf_Email_Tela_Cadastro_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Email_Tela_Cadastro_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Email_Tela_Cadastro_FuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Cancelar_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Editar_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Salvar_Tela_Cadastro_Funcionario;
    private javax.swing.JButton Jbtn_Treinamentos_Tela_Cadastro_Funcionario;
    private javax.swing.JComboBox<String> Jcbbx_Turno_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Area_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_CPF_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Cadastrar_Tela_Adicionar_Funcionario;
    private javax.swing.JLabel Jlbl_Cargo_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Codigo_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Contato_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Email_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Foto_Funcionario_Tela_Adicionar_Funcionario;
    private javax.swing.JLabel Jlbl_IdentificacaoEquipe_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Identificacao_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Maticula_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Nome_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Numero_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Sobrenome_Tela_Cadastro_Funcionario;
    private javax.swing.JLabel Jlbl_Turno_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel Jpnl_Area_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel Jpnl_Contato_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel Jpnl_Identificacao_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_CPF_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Cargo_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Codigo_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Email_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_IdentificacaoEquipe_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Matricula_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Nome_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Numero_Tela_Cadastro_Funcionario;
    private javax.swing.JTextField Jtxtf_Sobrenome_Tela_Cadastro_Funcionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
