/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas_Setor;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author renan_8tvcd4n
 */
public class Tela_Cadastro_Setor extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastro_Setor
     */
    public Tela_Cadastro_Setor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlbl_Titulo_CadSet = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Jlbl_Nome_CadSet = new javax.swing.JLabel();
        Jlbl_Sigla_CadSet = new javax.swing.JLabel();
        Jtxtf_Nome_CadSet = new javax.swing.JTextField();
        Jtxtf_Sigla_CadSet = new javax.swing.JTextField();
        Jbtn_Cadastrar_CadSetor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jlbl_Titulo_CadSet.setBackground(new java.awt.Color(249, 246, 226));

        jPanel2.setBackground(new java.awt.Color(243, 228, 188));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Jlbl_Nome_CadSet.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jlbl_Nome_CadSet.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Nome_CadSet.setText("Nome:");

        Jlbl_Sigla_CadSet.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jlbl_Sigla_CadSet.setForeground(new java.awt.Color(0, 0, 0));
        Jlbl_Sigla_CadSet.setText("Sigla:");

        Jtxtf_Nome_CadSet.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Nome_CadSet.setMaximumSize(new java.awt.Dimension(200, 30));
        Jtxtf_Nome_CadSet.setMinimumSize(new java.awt.Dimension(200, 30));
        Jtxtf_Nome_CadSet.setPreferredSize(new java.awt.Dimension(200, 30));

        Jtxtf_Sigla_CadSet.setBackground(new java.awt.Color(255, 255, 255));
        Jtxtf_Sigla_CadSet.setMaximumSize(new java.awt.Dimension(200, 30));
        Jtxtf_Sigla_CadSet.setMinimumSize(new java.awt.Dimension(200, 30));
        Jtxtf_Sigla_CadSet.setPreferredSize(new java.awt.Dimension(200, 30));

        Jbtn_Cadastrar_CadSetor.setBackground(new java.awt.Color(243, 236, 196));
        Jbtn_Cadastrar_CadSetor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jbtn_Cadastrar_CadSetor.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Cadastrar_CadSetor.setText("Cadastrar");
        Jbtn_Cadastrar_CadSetor.setMaximumSize(new java.awt.Dimension(120, 45));
        Jbtn_Cadastrar_CadSetor.setMinimumSize(new java.awt.Dimension(120, 45));
        Jbtn_Cadastrar_CadSetor.setPreferredSize(new java.awt.Dimension(120, 45));
        Jbtn_Cadastrar_CadSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Cadastrar_CadSetorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtxtf_Nome_CadSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlbl_Nome_CadSet))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtxtf_Sigla_CadSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlbl_Sigla_CadSet, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(Jbtn_Cadastrar_CadSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_Nome_CadSet)
                    .addComponent(Jlbl_Sigla_CadSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtf_Nome_CadSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtxtf_Sigla_CadSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(Jbtn_Cadastrar_CadSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro Setor");

        javax.swing.GroupLayout Jlbl_Titulo_CadSetLayout = new javax.swing.GroupLayout(Jlbl_Titulo_CadSet);
        Jlbl_Titulo_CadSet.setLayout(Jlbl_Titulo_CadSetLayout);
        Jlbl_Titulo_CadSetLayout.setHorizontalGroup(
            Jlbl_Titulo_CadSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jlbl_Titulo_CadSetLayout.createSequentialGroup()
                .addGroup(Jlbl_Titulo_CadSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jlbl_Titulo_CadSetLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Jlbl_Titulo_CadSetLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        Jlbl_Titulo_CadSetLayout.setVerticalGroup(
            Jlbl_Titulo_CadSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jlbl_Titulo_CadSetLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlbl_Titulo_CadSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlbl_Titulo_CadSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_Cadastrar_CadSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Cadastrar_CadSetorActionPerformed
        Connection connection = null;
        PreparedStatement statement = null;
        
        String url = "jdbc:mysql://localhost:3306/db_agenda_curso";
        String user = "root";
        String psswrd = "";
        
        try {
            connection = DriverManager.getConnection(url, user, psswrd);
            String query = "INSERT INTO setor(nome, sigla) values(?, ?)"; // adicionar tambem id instrutor
            statement = connection.prepareStatement(query);
            
            statement.setString(1, Jtxtf_Nome_CadSet.getText());
            statement.setString(2, Jtxtf_Sigla_CadSet.getText());
            
            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Equipe Criada");
        } catch (SQLException erro){
            JOptionPane.showMessageDialog(null, "Erro: " + erro.getMessage());
        }
    }//GEN-LAST:event_Jbtn_Cadastrar_CadSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Setor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Cadastrar_CadSetor;
    private javax.swing.JLabel Jlbl_Nome_CadSet;
    private javax.swing.JLabel Jlbl_Sigla_CadSet;
    private javax.swing.JPanel Jlbl_Titulo_CadSet;
    private javax.swing.JTextField Jtxtf_Nome_CadSet;
    private javax.swing.JTextField Jtxtf_Sigla_CadSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
